"""Add abbreviation column to state model

Revision ID: e9b8d8473f07
Revises: 5ec9068ad364
Create Date: 2020-04-14 02:53:20.802425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b8d8473f07'
down_revision = '5ec9068ad364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('State', sa.Column('abbreviation', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('State', 'abbreviation')
    # ### end Alembic commands ###
